### ISSUE TITLE
support for mailchimp goals

### ISSUE THREAD

**Issue by sperand-io** [segment-integrations/integration-mailchimp#3]
http://kb.mailchimp.com/integrations/other-integrations/integrate-goal-with-mailchimp?t=1422037639&v=230&enc=514bcd5fdf6d163bce218fc4849f34298e0412f41738dcc0489c6754cb3d535c

https://segment.zendesk.com/agent/tickets/23397

whoa. mailchimp went and added behavioral / event-based emails and automations. i think we should definitely support this. 

@amillet89 @harrietgrace @ndhoule

**Comment by ndhoule** [comment]
FYI--On our radar, but not actively being worked on:

https://segment.zendesk.com/agent/tickets/22376
https://trello.com/c/UjddWv5S/80-mailchimp-add-goals-support

**Comment by sperand-io** [comment]
Success Engineering is taking ownership of this — should be an easy addition. And who knows, perhaps @hden will beat us to it!

I don't think we'll want to add any kind of mapping for Segment Events —> Mailchimp goals. Rather, we'll just encourage (read: require) users to use their Segment event names as the MC goal names here: 

![](https://cloudup.com/cJciL7bMREg+)

Docs for the `record_goal` API endpoint: https://apidocs.mailchimp.com/api/2.0/#goal-methods

**Comment by sperand-io** [comment]
Upon further review, the server-side implementation would [require a mailchimp campaign id](https://apidocs.mailchimp.com/api/2.0/#goal-methods) to send them a goal, as apparently these goals are campaign scoped. 

We can certainly just ensure for a custom context field on `.track()` and require users pass this themselves, but I wonder if there might be a way for us to add a packaged component that loads their library, gets the campaignId, and attaches it in that field to all subsequent outbound track calls *automatically*? ie. It wouldn't actually make any calls to mailchimp; rather, it would just enrich the calls to segments servers so that we could use the information there,

ATM, there is no prior art for client-side and server-side libs playing nicely together, and this may be totally out of scope, but it is an interesting use case and not unlike those from hasoffers, dataxu, and some others who have server-side APIs and are willing to go direct but are reliant on a campaignId of sorts (right now they use `context.referrer.id`). Perhaps this could be applied to those as well?

would like to get thoughts on the above from @calvinfo and @amillet89 before moving forward.

**Comment by calvinfo** [comment]
From super brief testing, I'm not sure how we'd automatically grab the
campaign id. It looks like they re-encode links to mailchimp and then issue
a temp redirect, so I don't think we can grab it from `document.referrer` :\

**Comment by hden** [comment]
AFAIK, Goal is more concerned with the source of user acquisition *i.e.* the campaign, which is often considered as a trait of an user identity and not necessary synced between client platforms. Perhaps we can encourage users to `identify()`?

On the other hand, a related feature of mailchimp, called [eCommerce360](http://kb.mailchimp.com/integrations/other-integrations/about-ecommerce360) fits very well with [ecommerce events](https://segment.com/docs/spec/ecommerce/), should I open another issue for that?

**Comment by chiplay** [comment]
We'd love to see an eCommerce360 integration with analytics.js!

**Comment by chiplay** [comment]
Any traction with implementing goals or eCommerce360?  I'd love to start sending goal and purchase events client side via analytics.js

**Comment by raisonon** [comment]
Any updates here (@chiplay)

**Comment by hankim813** [comment]
The Mailchimp integration is now on their newest API v3.0 and I'm not able to find any official docs from Mailchimp's end on how to do this. 

I don't think this is available yet on the 3.0 so will close this issue until MC provides support for it.
